apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-nodejs-app-v29
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advanced-nodejs-app-v29
  template:
    metadata:
      labels:
        app: advanced-nodejs-app-v29
    spec:
      containers:
        - name: app
          image: hoangphuc842/advanced-nodejs-app-v29:@sha256:5d296b1d1bf7e30c67cc7dcd53d5f9438afa4e770a6d0594562c0ab97f75f453
          ports:
            - containerPort: 8080
