apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-nodejs-app-v29
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advanced-nodejs-app-v29
  template:
    metadata:
      labels:
        app: advanced-nodejs-app-v29
    spec:
      containers:
        - name: app
          image: hoangphuc842/advanced-nodejs-app-v29:@sha256:3864ab3340c1b5c0730dfccb21118c5ffac604eaa17cf7c613fe5cda31bb58f0
          ports:
            - containerPort: 8080
